
[keys.normal]
"h" = "move_char_left" # "h" | "left"
"left" = "move_char_left" # "h" | "left"
"j" = "move_visual_line_down" # "j" | "down"
"down" = "move_visual_line_down" # "j" | "down"
"k" = "move_visual_line_up" # "k" | "up"
"up" = "move_visual_line_up" # "k" | "up"
"l" = "move_char_right" # "l" | "right"
"right" = "move_char_right" # "l" | "right"
"t" = "find_till_char" # "t"
"f" = "find_next_char" # "f"
"T" = "till_prev_char" # "T"
"F" = "find_prev_char" # "F"
"r" = "replace" # "r"
"R" = "replace_with_yanked" # "R"
"A-." = "repeat_last_motion" # "A-."
"~" = "switch_case" # "~"
"`" = "switch_to_lowercase" # "`"
"A-`" = "switch_to_uppercase" # "A-`"
"home" = "goto_line_start" # "home"
"end" = "goto_line_end" # "end"
"w" = "move_next_word_start" # "w"
"b" = "move_prev_word_start" # "b"
"e" = "move_next_word_end" # "e"
"W" = "move_next_long_word_start" # "W"
"B" = "move_prev_long_word_start" # "B"
"E" = "move_next_long_word_end" # "E"
"v" = "select_mode" # "v"
"G" = "goto_line" # "G"

":" = "command_mode" # ":"
"i" = "insert_mode" # "i"
"I" = "insert_at_line_start" # "I"
"a" = "append_mode" # "a"
"A" = "insert_at_line_end" # "A"
"o" = "open_below" # "o"
"O" = "open_above" # "O"
"d" = "delete_selection" # "d"
"A-d" = "delete_selection_noyank" # "A-d"
"c" = "change_selection" # "c"
"A-c" = "change_selection_noyank" # "A-c"
"C" = "copy_selection_on_next_line" # "C"
"A-C" = "copy_selection_on_prev_line" # "A-C"
"s" = "select_regex" # "s"
"A-s" = "split_selection_on_newline" # "A-s"
# error? "A-minus" = "merge_selections" # "A-minus"
"A-_" = "merge_consecutive_selections" # "A-_"
"S" = "split_selection" # "S"
";" = "collapse_selection" # ";"
"A-;" = "flip_selections" # "A-;"
"A-o" = "expand_selection" # "A-o" | "A-up"
"A-up" = "expand_selection" # "A-o" | "A-up"
"A-i" = "shrink_selection" # "A-i" | "A-down"
"A-down" = "shrink_selection" # "A-i" | "A-down"
"A-p" = "select_prev_sibling" # "A-p" | "A-left"
"A-left" = "select_prev_sibling" # "A-p" | "A-left"
"A-n" = "select_next_sibling" # "A-n" | "A-right"
"A-right" = "select_next_sibling" # "A-n" | "A-right"
# error? "A-e" = "move_parent_node_end" # "A-e"
# error? "A-b" = "move_parent_node_start" # "A-b"
"%" = "select_all" # "%"
"x" = "extend_line_below" # "x"
"X" = "extend_to_line_bounds" # "X"
"A-x" = "shrink_to_line_bounds" # "A-x"

"/" = "search" # "/"
"?" = "rsearch" # "?"
"n" = "search_next" # "n"
"N" = "search_prev" # "N"
"*" = "search_selection" # "*"
"u" = "undo" # "u"
"U" = "redo" # "U"
"A-u" = "earlier" # "A-u"
"A-U" = "later" # "A-U"
"y" = "yank" # "y"
"p" = "paste_after" # "p"
"P" = "paste_before" # "P"
"Q" = "record_macro" # "Q"
"q" = "replay_macro" # "q"
">" = "indent" # ">"
"<" = "unindent" # "<"
"=" = "format_selections" # "="
"J" = "join_selections" # "J"
"A-J" = "join_selections_space" # "A-J"
"K" = "keep_selections" # "K"
"A-K" = "remove_selections" # "A-K"
"," = "keep_primary_selection" # ","
"A-," = "remove_primary_selection" # "A-,"

# "q" = "record_macro" # "q"
#"Q" = "replay_macro" # "Q"

"&" = "align_selections" # "&"
"_" = "trim_selections" # "_"
"(" = "rotate_selections_backward" # "("
")" = "rotate_selections_forward" # ")"
"A-(" = "rotate_selection_contents_backward" # "A-("
"A-)" = "rotate_selection_contents_forward" # "A-)"
"A-:" = "ensure_selections_forward" # "A-:"
"esc" = "normal_mode" # "esc"
"C-b" = "page_up" # "C-b" | "pageup"
"pageup" = "page_up" # "C-b" | "pageup"
"C-f" = "page_down" # "C-f" | "pagedown"
"pagedown" = "page_down" # "C-f" | "pagedown"
"C-u" = "half_page_up" # "C-u"
"C-d" = "half_page_down" # "C-d"

"C-c" = "toggle_comments" # "C-c"
"C-i" = "jump_forward" # "C-i" | "tab" // tab == <C-i>
"tab" = "jump_forward" # "C-i" | "tab" // tab == <C-i>
"C-o" = "jump_backward" # "C-o"
"C-s" = "save_selection" # "C-s"

"\"" = "select_register" # "\""
"|" = "shell_pipe" # "|"
"A-|" = "shell_pipe_to" # "A-|"
"!" = "shell_insert_output" # "!"
"A-!" = "shell_append_output" # "A-!"
"$" = "shell_keep_pipe" # "$"
"C-z" = "suspend" # "C-z"
"C-a" = "increment" # "C-a"
"C-x" = "decrement" # "C-x"

[keys.normal.g] # [keys.normal.g]
"g" = "goto_file_start" # "g"
"e" = "goto_last_line" # "e"
"f" = "goto_file" # "f"
"h" = "goto_line_start" # "h"
"l" = "goto_line_end" # "l"
"s" = "goto_first_nonwhitespace" # "s"
"d" = "goto_definition" # "d"
"D" = "goto_declaration" # "D"
"y" = "goto_type_definition" # "y"
"r" = "goto_reference" # "r"
"i" = "goto_implementation" # "i"
"t" = "goto_window_top" # "t"
"c" = "goto_window_center" # "c"
"b" = "goto_window_bottom" # "b"
"a" = "goto_last_accessed_file" # "a"
"m" = "goto_last_modified_file" # "m"
"n" = "goto_next_buffer" # "n"
"p" = "goto_previous_buffer" # "p"
"k" = "move_line_up" # "k"
"j" = "move_line_down" # "j"
"." = "goto_last_modification" # "."

[keys.normal.m] # [keys.normal.m]
"m" = "match_brackets" # "m"
"s" = "surround_add" # "s"
"r" = "surround_replace" # "r"
"d" = "surround_delete" # "d"
"a" = "select_textobject_around" # "a"
"i" = "select_textobject_inner" # "i"

[keys.normal."["] # [keys.normal."["]
"d" = "goto_prev_diag" # "d"
"D" = "goto_first_diag" # "D"
"g" = "goto_prev_change" # "g"
"G" = "goto_first_change" # "G"
"f" = "goto_prev_function" # "f"
"t" = "goto_prev_class" # "t"
"a" = "goto_prev_parameter" # "a"
"c" = "goto_prev_comment" # "c"
"T" = "goto_prev_test" # "T"
"p" = "goto_prev_paragraph" # "p"
"space" = "add_newline_above" # "space"

[keys.normal."]"] # [keys.normal."]"]
"d" = "goto_next_diag" # "d"
"D" = "goto_last_diag" # "D"
"g" = "goto_next_change" # "g"
"G" = "goto_last_change" # "G"
"f" = "goto_next_function" # "f"
"t" = "goto_next_class" # "t"
"a" = "goto_next_parameter" # "a"
"c" = "goto_next_comment" # "c"
"T" = "goto_next_test" # "T"
"p" = "goto_next_paragraph" # "p"
"space" = "add_newline_below" # "space"

[keys.normal.C-w] # [keys.normal.C-w]
"C-w" = "rotate_view" # "C-w" | "w"
"w" = "rotate_view" # "C-w" | "w"
"C-s" = "hsplit" # "C-s" | "s"
"s" = "hsplit" # "C-s" | "s"
"C-v" = "vsplit" # "C-v" | "v"
"v" = "vsplit" # "C-v" | "v"
"C-t" = "transpose_view" # "C-t" | "t"
"t" = "transpose_view" # "C-t" | "t"
"f" = "goto_file_hsplit" # "f"
"F" = "goto_file_vsplit" # "F"
"C-q" = "wclose" # "C-q" | "q"
"q" = "wclose" # "C-q" | "q"
"C-o" = "wonly" # "C-o" | "o"
"o" = "wonly" # "C-o" | "o"
"C-h" = "jump_view_left" # "C-h" | "h" | "left"
"h" = "jump_view_left" # "C-h" | "h" | "left"
"left" = "jump_view_left" # "C-h" | "h" | "left"
"C-j" = "jump_view_down" # "C-j" | "j" | "down"
"j" = "jump_view_down" # "C-j" | "j" | "down"
"down" = "jump_view_down" # "C-j" | "j" | "down"
"C-k" = "jump_view_up" # "C-k" | "k" | "up"
"k" = "jump_view_up" # "C-k" | "k" | "up"
"up" = "jump_view_up" # "C-k" | "k" | "up"
"C-l" = "jump_view_right" # "C-l" | "l" | "right"
"l" = "jump_view_right" # "C-l" | "l" | "right"
"right" = "jump_view_right" # "C-l" | "l" | "right"
"L" = "swap_view_right" # "L"
"K" = "swap_view_up" # "K"
"H" = "swap_view_left" # "H"
"J" = "swap_view_down" # "J"

[keys.normal.C-w.n] # [keys.normal.C-w.n]
"C-s" = "hsplit_new" # "C-s" | "s"
"s" = "hsplit_new" # "C-s" | "s"
"C-v" = "vsplit_new" # "C-v" | "v"
"v" = "vsplit_new" # "C-v" | "v"

[keys.normal.space]
"f" = "file_picker" # "f"
"F" = "file_picker_in_current_directory" # "F"
"b" = "buffer_picker" # "b"
"j" = "jumplist_picker" # "j"
"s" = "symbol_picker" # "s"
"S" = "workspace_symbol_picker" # "S"
"d" = "diagnostics_picker" # "d"
"D" = "workspace_diagnostics_picker" # "D"
"a" = "code_action" # "a"
"'" = "last_picker" # "'"

"y" = "yank_joined_to_clipboard" # "y"
"Y" = "yank_main_selection_to_clipboard" # "Y"
"p" = "paste_clipboard_after" # "p"
"P" = "paste_clipboard_before" # "P"
"R" = "replace_selections_with_clipboard" # "R"
"/" = "global_search" # "/"
"k" = "hover" # "k"
"r" = "rename_symbol" # "r"
"h" = "select_references_to_symbol_under_cursor" # "h"
"?" = "command_palette" # "?"

[keys.normal.space.g] # [keys.normal.space.g]
"l" = "dap_launch" # "l"
"r" = "dap_restart" # "r"
"b" = "dap_toggle_breakpoint" # "b"
"c" = "dap_continue" # "c"
"h" = "dap_pause" # "h"
"i" = "dap_step_in" # "i"
"o" = "dap_step_out" # "o"
"n" = "dap_next" # "n"
"v" = "dap_variables" # "v"
"t" = "dap_terminate" # "t"
"C-c" = "dap_edit_condition" # "C-c"
"C-l" = "dap_edit_log" # "C-l"
"e" = "dap_enable_exceptions" # "e"
"E" = "dap_disable_exceptions" # "E"

[keys.normal.space.g.s] # [keys.normal.space.g.s]
"t" = "dap_switch_thread" # "t"
"f" = "dap_switch_stack_frame" # "f"

[keys.normal.space.w] # [keys.normal.space.w]
"C-w" = "rotate_view" # "C-w" | "w"
"w" = "rotate_view" # "C-w" | "w"
"C-s" = "hsplit" # "C-s" | "s"
"s" = "hsplit" # "C-s" | "s"
"C-v" = "vsplit" # "C-v" | "v"
"v" = "vsplit" # "C-v" | "v"
"C-t" = "transpose_view" # "C-t" | "t"
"t" = "transpose_view" # "C-t" | "t"
"f" = "goto_file_hsplit" # "f"
"F" = "goto_file_vsplit" # "F"
"C-q" = "wclose" # "C-q" | "q"
"q" = "wclose" # "C-q" | "q"
"C-o" = "wonly" # "C-o" | "o"
"o" = "wonly" # "C-o" | "o"
"C-h" = "jump_view_left" # "C-h" | "h" | "left"
"h" = "jump_view_left" # "C-h" | "h" | "left"
"left" = "jump_view_left" # "C-h" | "h" | "left"
"C-j" = "jump_view_down" # "C-j" | "j" | "down"
"j" = "jump_view_down" # "C-j" | "j" | "down"
"down" = "jump_view_down" # "C-j" | "j" | "down"
"C-k" = "jump_view_up" # "C-k" | "k" | "up"
"k" = "jump_view_up" # "C-k" | "k" | "up"
"up" = "jump_view_up" # "C-k" | "k" | "up"
"C-l" = "jump_view_right" # "C-l" | "l" | "right"
"l" = "jump_view_right" # "C-l" | "l" | "right"
"right" = "jump_view_right" # "C-l" | "l" | "right"
"H" = "swap_view_left" # "H"
"J" = "swap_view_down" # "J"
"K" = "swap_view_up" # "K"
"L" = "swap_view_right" # "L"

[keys.normal.space.w.n] # [keys.normal.space.w.n]
"C-s" = "hsplit_new" # "C-s" | "s"
"s" = "hsplit_new" # "C-s" | "s"
"C-v" = "vsplit_new" # "C-v" | "v"
"v" = "vsplit_new" # "C-v" | "v"

[keys.normal.z] # [keys.normal.z]
"z" = "align_view_center" # "z" | "c"
"c" = "align_view_center" # "z" | "c"
"t" = "align_view_top" # "t"
"b" = "align_view_bottom" # "b"
"m" = "align_view_middle" # "m"
"k" = "scroll_up" # "k" | "up"
"up" = "scroll_up" # "k" | "up"
"j" = "scroll_down" # "j" | "down"
"down" = "scroll_down" # "j" | "down"
"C-b" = "page_up" # "C-b" | "pageup"
"pageup" = "page_up" # "C-b" | "pageup"
"C-f" = "page_down" # "C-f" | "pagedown"
"pagedown" = "page_down" # "C-f" | "pagedown"
"C-u" = "half_page_up" # "C-u" | "backspace"
"backspace" = "half_page_up" # "C-u" | "backspace"
"C-d" = "half_page_down" # "C-d" | "space"
"space" = "half_page_down" # "C-d" | "space"
"/" = "search" # "/"
"?" = "rsearch" # "?"
"n" = "search_next" # "n"
"N" = "search_prev" # "N"

[keys.normal.Z] # [keys.normal.Z]
"z" = "align_view_center" # "z" | "c"
"c" = "align_view_center" # "z" | "c"
"t" = "align_view_top" # "t"
"b" = "align_view_bottom" # "b"
"m" = "align_view_middle" # "m"
"k" = "scroll_up" # "k" | "up"
"up" = "scroll_up" # "k" | "up"
"j" = "scroll_down" # "j" | "down"
"down" = "scroll_down" # "j" | "down"
"C-b" = "page_up" # "C-b" | "pageup"
"pageup" = "page_up" # "C-b" | "pageup"
"C-f" = "page_down" # "C-f" | "pagedown"
"pagedown" = "page_down" # "C-f" | "pagedown"
"C-u" = "half_page_up" # "C-u" | "backspace"
"backspace" = "half_page_up" # "C-u" | "backspace"
"C-d" = "half_page_down" # "C-d" | "space"
"space" = "half_page_down" # "C-d" | "space"
"/" = "search" # "/"
"?" = "rsearch" # "?"
"n" = "search_next" # "n"
"N" = "search_prev" # "N"

[keys.select]
"h" = "extend_char_left" # "h" | "left"
"left" = "extend_char_left" # "h" | "left"
"j" = "extend_visual_line_down" # "j" | "down"
"down" = "extend_visual_line_down" # "j" | "down"
"k" = "extend_visual_line_up" # "k" | "up"
"up" = "extend_visual_line_up" # "k" | "up"
"l" = "extend_char_right" # "l" | "right"
"right" = "extend_char_right" # "l" | "right"
"w" = "extend_next_word_start" # "w"
"b" = "extend_prev_word_start" # "b"
"e" = "extend_next_word_end" # "e"
"W" = "extend_next_long_word_start" # "W"
"B" = "extend_prev_long_word_start" # "B"
"E" = "extend_next_long_word_end" # "E"
# error? "A-e" = "extend_parent_node_end" # "A-e"
# error? "A-b" = "extend_parent_node_start" # "A-b"
"n" = "extend_search_next" # "n"
"N" = "extend_search_prev" # "N"
"t" = "extend_till_char" # "t"
"f" = "extend_next_char" # "f"
"T" = "extend_till_prev_char" # "T"
"F" = "extend_prev_char" # "F"
"home" = "extend_to_line_start" # "home"
"end" = "extend_to_line_end" # "end"
"esc" = "exit_select_mode" # "esc"
"v" = "normal_mode" # "v"

[keys.select.g] # [keys.select.g]
"k" = "extend_line_up" # "k"
"j" = "extend_line_down" # "j"

[keys.insert]
"esc" = "normal_mode" # "esc"
"C-s" = "commit_undo_checkpoint" # "C-s"
"C-x" = "completion" # "C-x"
"C-r" = "insert_register" # "C-r"
"C-w" = "delete_word_backward" # "C-w" | "A-backspace"
"A-backspace" = "delete_word_backward" # "C-w" | "A-backspace"
"A-d" = "delete_word_forward" # "A-d" | "A-del"
"A-del" = "delete_word_forward" # "A-d" | "A-del"
"C-u" = "kill_to_line_start" # "C-u"
"C-k" = "kill_to_line_end" # "C-k"
"C-h" = "delete_char_backward" # "C-h" | "backspace" | "S-backspace"
"backspace" = "delete_char_backward" # "C-h" | "backspace" | "S-backspace"
"S-backspace" = "delete_char_backward" # "C-h" | "backspace" | "S-backspace"
"C-d" = "delete_char_forward" # "C-d" | "del"
"del" = "delete_char_forward" # "C-d" | "del"
"C-j" = "insert_newline" # "C-j" | "ret"
"ret" = "insert_newline" # "C-j" | "ret"
# error? "tab" = "smart_tab" # "tab"
"S-tab" = "insert_tab" # "S-tab"
"up" = "move_visual_line_up" # "up"
"down" = "move_visual_line_down" # "down"
"left" = "move_char_left" # "left"
"right" = "move_char_right" # "right"
"pageup" = "page_up" # "pageup"
"pagedown" = "page_down" # "pagedown"
"home" = "goto_line_start" # "home"
"end" = "goto_line_end_newline" # "end"
